version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    label: "maintenance"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/"
    label: "maintenance"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    label: "maintenance"
    schedule:
      interval: "monthly"
    groups:
      emotion:
        patterns:
          - '@emotion/**'
      jupyterlab:
        patterns:
          - '@jupyterlab/*'
      mui:
        patterns:
          - '@mui/*'
