name: naavre-workflow-jl-dev

services:
  # workflow-service:
  #   image: ghcr.io/naavre/naavre-workflow-service:v0.0.0
  #   ports:
  #     - "127.0.0.1:62438:8000"

  catalogue-service:
    image: ghcr.io/naavre/naavre-catalogue-service:v0.1.1
    ports:
      - '127.0.0.1:56848:8000'
    volumes:
      - ./catalogue-fixtures.json:/code/app/fixtures.json
    environment:
      DEV_MODE: true
      VERIFY_SSL: false
      DISABLE_AUTH: true
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: example@example.org
      DB_HOST: catalogue-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres-password
      DB_NAME: postgres
      OIDC_CONFIGURATION_URL: https://naavre-dev.minikube.test/auth/realms/vre/.well-known/openid-configuration

  catalogue-db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres-password
